{% set name = "twisted-iocpsupport" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/twisted-iocpsupport-{{ version }}.tar.gz
  sha256: 858096c0d15e33f15ac157f455d8f86f2f2cdd223963e58c0f682a3af8362d89

build:
  number: 0
  skip: true  # [not win]
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - python

test:
  imports:
    - twisted_iocpsupport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/twisted/twisted-iocpsupport
  summary: An extension for use in the twisted I/O Completion Ports reactor.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nehaljwani
