{% set name = "twisted-iocpsupport" %}
{% set version = "25.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8c4271520f60b91af5a29c0e822a433eb855778659e4347c6f65b73d1c99d3fe

build:
  number: 0
  skip: true  # [not win]
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - twisted_iocpsupport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/twisted/twisted-iocpsupport
  summary: An extension for use in the twisted I/O Completion Ports reactor.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nehaljwani
